# O prefíxo do idioma padrão
defaultlanguage: 'pt'
timezone: 'America/Sao_Paulo'
# Configurações de armazenamento
database:
  mysql:
    user: 'JscpvRjROx'
    password: 'KJzMmNeUXz'
    host: 'remotemysql.com'
    port: 3306
  sqlite:
    folder: 'data'
# Habilitar suporte para exibição de nomes de encantamentos acima de 'X' (10)?
enchants:
  enabled: false
  levels:
    1: 'I'
    2: 'II'
    3: 'III'
    4: 'IV'
    5: 'V'
    6: 'VI'
    7: 'VII'
    8: 'VIII'
    9: 'IX'
    10: 'X'
    11: 'XI'
    12: 'XII'
    13: 'XIII'
    14: 'XIV'
    15: 'XV'
    16: 'XVI'
    17: 'XVII'
    18: 'XVIII'
    19: 'XIX'
    20: 'XX'